// Copyright IBM Corp. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: transaction/encode_transaction_api.proto

package transaction

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// EncodedTransactionRequest is a TODO and FIXME comment.
type EncodedTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *EncodedTransactionRequest) Reset() {
	*x = EncodedTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_encode_transaction_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedTransactionRequest) ProtoMessage() {}

func (x *EncodedTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_encode_transaction_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedTransactionRequest.ProtoReflect.Descriptor instead.
func (*EncodedTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_encode_transaction_api_proto_rawDescGZIP(), []int{0}
}

func (x *EncodedTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// EncodedTransactionResponse is a TODO and FIXME comment.
type EncodedTransactionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid               []byte `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	EncodedTransaction []byte `protobuf:"bytes,2,opt,name=encoded_transaction,json=encodedTransaction,proto3" json:"encoded_transaction,omitempty"`
}

func (x *EncodedTransactionResponse) Reset() {
	*x = EncodedTransactionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transaction_encode_transaction_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedTransactionResponse) ProtoMessage() {}

func (x *EncodedTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_encode_transaction_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedTransactionResponse.ProtoReflect.Descriptor instead.
func (*EncodedTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_encode_transaction_api_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedTransactionResponse) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *EncodedTransactionResponse) GetEncodedTransaction() []byte {
	if x != nil {
		return x.EncodedTransaction
	}
	return nil
}

var File_transaction_encode_transaction_api_proto protoreflect.FileDescriptor

var file_transaction_encode_transaction_api_proto_rawDesc = []byte{
	0x0a, 0x28, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x19, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x61, 0x0a, 0x1a, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69,
	0x64, 0x12, 0x2f, 0x0a, 0x13, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x32, 0x7d, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x65, 0x0a, 0x12, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x62, 0x6d, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x74, 0x69, 0x6b, 0x2f, 0x62, 0x61, 0x74, 0x69, 0x6b, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transaction_encode_transaction_api_proto_rawDescOnce sync.Once
	file_transaction_encode_transaction_api_proto_rawDescData = file_transaction_encode_transaction_api_proto_rawDesc
)

func file_transaction_encode_transaction_api_proto_rawDescGZIP() []byte {
	file_transaction_encode_transaction_api_proto_rawDescOnce.Do(func() {
		file_transaction_encode_transaction_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_transaction_encode_transaction_api_proto_rawDescData)
	})
	return file_transaction_encode_transaction_api_proto_rawDescData
}

var file_transaction_encode_transaction_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_encode_transaction_api_proto_goTypes = []interface{}{
	(*EncodedTransactionRequest)(nil),  // 0: transaction.EncodedTransactionRequest
	(*EncodedTransactionResponse)(nil), // 1: transaction.EncodedTransactionResponse
	(*Transaction)(nil),                // 2: transaction.Transaction
}
var file_transaction_encode_transaction_api_proto_depIdxs = []int32{
	2, // 0: transaction.EncodedTransactionRequest.transaction:type_name -> transaction.Transaction
	0, // 1: transaction.EncodeTransactionAPI.EncodedTransaction:input_type -> transaction.EncodedTransactionRequest
	1, // 2: transaction.EncodeTransactionAPI.EncodedTransaction:output_type -> transaction.EncodedTransactionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_encode_transaction_api_proto_init() }
func file_transaction_encode_transaction_api_proto_init() {
	if File_transaction_encode_transaction_api_proto != nil {
		return
	}
	file_transaction_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_transaction_encode_transaction_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transaction_encode_transaction_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedTransactionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transaction_encode_transaction_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_encode_transaction_api_proto_goTypes,
		DependencyIndexes: file_transaction_encode_transaction_api_proto_depIdxs,
		MessageInfos:      file_transaction_encode_transaction_api_proto_msgTypes,
	}.Build()
	File_transaction_encode_transaction_api_proto = out.File
	file_transaction_encode_transaction_api_proto_rawDesc = nil
	file_transaction_encode_transaction_api_proto_goTypes = nil
	file_transaction_encode_transaction_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EncodeTransactionAPIClient is the client API for EncodeTransactionAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EncodeTransactionAPIClient interface {
	// EncodedTransaction is a TODO and FIXME comment.
	EncodedTransaction(ctx context.Context, in *EncodedTransactionRequest, opts ...grpc.CallOption) (*EncodedTransactionResponse, error)
}

type encodeTransactionAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEncodeTransactionAPIClient(cc grpc.ClientConnInterface) EncodeTransactionAPIClient {
	return &encodeTransactionAPIClient{cc}
}

func (c *encodeTransactionAPIClient) EncodedTransaction(ctx context.Context, in *EncodedTransactionRequest, opts ...grpc.CallOption) (*EncodedTransactionResponse, error) {
	out := new(EncodedTransactionResponse)
	err := c.cc.Invoke(ctx, "/transaction.EncodeTransactionAPI/EncodedTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncodeTransactionAPIServer is the server API for EncodeTransactionAPI service.
type EncodeTransactionAPIServer interface {
	// EncodedTransaction is a TODO and FIXME comment.
	EncodedTransaction(context.Context, *EncodedTransactionRequest) (*EncodedTransactionResponse, error)
}

// UnimplementedEncodeTransactionAPIServer can be embedded to have forward compatible implementations.
type UnimplementedEncodeTransactionAPIServer struct {
}

func (*UnimplementedEncodeTransactionAPIServer) EncodedTransaction(context.Context, *EncodedTransactionRequest) (*EncodedTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncodedTransaction not implemented")
}

func RegisterEncodeTransactionAPIServer(s *grpc.Server, srv EncodeTransactionAPIServer) {
	s.RegisterService(&_EncodeTransactionAPI_serviceDesc, srv)
}

func _EncodeTransactionAPI_EncodedTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncodedTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncodeTransactionAPIServer).EncodedTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.EncodeTransactionAPI/EncodedTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncodeTransactionAPIServer).EncodedTransaction(ctx, req.(*EncodedTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EncodeTransactionAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.EncodeTransactionAPI",
	HandlerType: (*EncodeTransactionAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncodedTransaction",
			Handler:    _EncodeTransactionAPI_EncodedTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/encode_transaction_api.proto",
}
