#!/bin/bash

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

cd protos
mkdir -p ../pkg/pb
for dir in $(find . -name '*.proto' -exec dirname {} \; | sort -u | grep -v googleapis); do
  protoc \
      --proto_path . \
      --proto_path googleapis \
      --go_out=../pkg/pb \
      --go-grpc_out=../pkg/pb \
      --grpc-gateway_out=../pkg/pb \
      --go_opt=paths=source_relative \
      --go-grpc_opt=paths=source_relative \
      --grpc-gateway_opt=logtostderr=true,paths=source_relative \
      "$dir"/*.proto
done
