#!/bin/bash

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

main() {
    >&2 echo "Running go test..."
    go test -race -cover -timeout 20m ./...
}

main
