#!/bin/bash

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

main() {
    declare -a test_dirs
    while IFS='' read -r line; do test_dirs+=("$line"); done < <(
        go list -f '{{ if or (len .TestGoFiles | ne 0) (len .XTestGoFiles | ne 0) }}{{ println .Dir }}{{ end }}' ./... | \
            grep integration | \
            sed s,"$PWD",.,g
        )

    >&2 printf "Running the following test suites:\n\n%s\n\nStarting tests...\n\n" "$(echo "${test_dirs[@]}" | tr -s ' ' '\n')"
    time ginkgo -keepGoing --slowSpecThreshold 60 -r -p "${test_dirs[@]}"
    echo
}

main
