#!/bin/bash

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

main() {
    local -a packages
    packages=$(go list ./... | grep -v integration)

    >&2 echo "Running go test..."
    time go test -race -cover -timeout 20m ${packages[@]}
    echo
    >&2 echo "Running tests with the goproto tag enabled..."
    time go test -race -cover -tags goproto -timeout 20m ${packages[@]}
}

main
