#!/bin/bash

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

govet() {
    >&2 echo Running go vet...
    go vet -c=5 ./...
}

protolint() {
    >&2 echo Running prototool lint...
    prototool lint protos
}

main() {
    protolint
    govet
}

main
