#!/bin/bash -e

# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

if [ ! "${GITHUB_REF#refs/heads/}" == "develop" ]; then
    exit 0
fi

commit_sha="${GITHUB_SHA}"
deploy_key="$(mktemp)"
cleanup() {
  rm -f "$deploy_key"
}
trap cleanup EXIT

printf "%s" "$PROMOTION_KEY" > "$deploy_key"
unset PROMOTION_KEY

git config color.diff always
git config user.email github-actions@noreply.github.com
git config user.name github-actions
git fetch origin main
git checkout main
git merge --ff-only "$commit_sha"
git show

git config url.git@github.com:.insteadOf https://github.com/
export GIT_SSH_COMMAND="ssh -i $deploy_key -o IdentitiesOnly=yes"
git push origin main
