// Copyright IBM Corp. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: tx/v1/resolved.proto

package txv1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A ResolvedState contains the information stored on the ledger and represents a
// StateReference that has been resolved to an output state generated by a previous
// committed transaction. While the contents of the state is generally opaque, the
// info provides ownership and schema information that can be inspected during validation.
type ResolvedState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid        []byte     `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	OutputIndex uint64     `protobuf:"varint,2,opt,name=output_index,json=outputIndex,proto3" json:"output_index,omitempty"`
	Info        *StateInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	State       []byte     `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ResolvedState) Reset() {
	*x = ResolvedState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_v1_resolved_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolvedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedState) ProtoMessage() {}

func (x *ResolvedState) ProtoReflect() protoreflect.Message {
	mi := &file_tx_v1_resolved_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedState.ProtoReflect.Descriptor instead.
func (*ResolvedState) Descriptor() ([]byte, []int) {
	return file_tx_v1_resolved_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvedState) GetTxid() []byte {
	if x != nil {
		return x.Txid
	}
	return nil
}

func (x *ResolvedState) GetOutputIndex() uint64 {
	if x != nil {
		return x.OutputIndex
	}
	return 0
}

func (x *ResolvedState) GetInfo() *StateInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *ResolvedState) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

// A Signer represents a Party that has signed a transaction and contains an
// identity that can be used to represent an owner or an interested party as
// well as a signature over some data.
type Signer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential []byte `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Signature  []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Signer) Reset() {
	*x = Signer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_v1_resolved_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signer) ProtoMessage() {}

func (x *Signer) ProtoReflect() protoreflect.Message {
	mi := &file_tx_v1_resolved_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signer.ProtoReflect.Descriptor instead.
func (*Signer) Descriptor() ([]byte, []int) {
	return file_tx_v1_resolved_proto_rawDescGZIP(), []int{1}
}

func (x *Signer) GetCredential() []byte {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Signer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// A ResolvedTransaction contains a transaction with all of its input and reference
// StateReferences that have been resolved to some ResolvedStates containing the actual
// data for the states. It also contains a list of signatures over the transaction
// that can be used for endorsement validation.
type ResolvedTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxId        []byte           `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Transaction *Transaction     `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Inputs      []*ResolvedState `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	References  []*ResolvedState `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	Signers     []*Signer        `protobuf:"bytes,5,rep,name=signers,proto3" json:"signers,omitempty"`
}

func (x *ResolvedTransaction) Reset() {
	*x = ResolvedTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tx_v1_resolved_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolvedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedTransaction) ProtoMessage() {}

func (x *ResolvedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_v1_resolved_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedTransaction.ProtoReflect.Descriptor instead.
func (*ResolvedTransaction) Descriptor() ([]byte, []int) {
	return file_tx_v1_resolved_proto_rawDescGZIP(), []int{2}
}

func (x *ResolvedTransaction) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *ResolvedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ResolvedTransaction) GetInputs() []*ResolvedState {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ResolvedTransaction) GetReferences() []*ResolvedState {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ResolvedTransaction) GetSigners() []*Signer {
	if x != nil {
		return x.Signers
	}
	return nil
}

var File_tx_v1_resolved_proto protoreflect.FileDescriptor

var file_tx_v1_resolved_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x78, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x74,
	0x78, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x06, 0x53,
	0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0xed, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x05, 0x74,
	0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x78, 0x49, 0x64,
	0x12, 0x34, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x78, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x73, 0x12, 0x34, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x78, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a,
	0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x78,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x62,
	0x6d, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x74, 0x69, 0x6b, 0x2f, 0x62, 0x61, 0x74, 0x69,
	0x6b, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x78, 0x2f, 0x76, 0x31, 0x3b, 0x74,
	0x78, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tx_v1_resolved_proto_rawDescOnce sync.Once
	file_tx_v1_resolved_proto_rawDescData = file_tx_v1_resolved_proto_rawDesc
)

func file_tx_v1_resolved_proto_rawDescGZIP() []byte {
	file_tx_v1_resolved_proto_rawDescOnce.Do(func() {
		file_tx_v1_resolved_proto_rawDescData = protoimpl.X.CompressGZIP(file_tx_v1_resolved_proto_rawDescData)
	})
	return file_tx_v1_resolved_proto_rawDescData
}

var file_tx_v1_resolved_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tx_v1_resolved_proto_goTypes = []interface{}{
	(*ResolvedState)(nil),       // 0: tx.v1.ResolvedState
	(*Signer)(nil),              // 1: tx.v1.Signer
	(*ResolvedTransaction)(nil), // 2: tx.v1.ResolvedTransaction
	(*StateInfo)(nil),           // 3: tx.v1.StateInfo
	(*Transaction)(nil),         // 4: tx.v1.Transaction
}
var file_tx_v1_resolved_proto_depIdxs = []int32{
	3, // 0: tx.v1.ResolvedState.info:type_name -> tx.v1.StateInfo
	4, // 1: tx.v1.ResolvedTransaction.transaction:type_name -> tx.v1.Transaction
	0, // 2: tx.v1.ResolvedTransaction.inputs:type_name -> tx.v1.ResolvedState
	0, // 3: tx.v1.ResolvedTransaction.references:type_name -> tx.v1.ResolvedState
	1, // 4: tx.v1.ResolvedTransaction.signers:type_name -> tx.v1.Signer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tx_v1_resolved_proto_init() }
func file_tx_v1_resolved_proto_init() {
	if File_tx_v1_resolved_proto != nil {
		return
	}
	file_tx_v1_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tx_v1_resolved_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolvedState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_v1_resolved_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tx_v1_resolved_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolvedTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tx_v1_resolved_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_v1_resolved_proto_goTypes,
		DependencyIndexes: file_tx_v1_resolved_proto_depIdxs,
		MessageInfos:      file_tx_v1_resolved_proto_msgTypes,
	}.Build()
	File_tx_v1_resolved_proto = out.File
	file_tx_v1_resolved_proto_rawDesc = nil
	file_tx_v1_resolved_proto_goTypes = nil
	file_tx_v1_resolved_proto_depIdxs = nil
}
